### ISSUE TITLE
파이콘 한국 2020 발표 주제 기획

### ISSUE THREAD

**Issue by dahlia** [planetarium/talks#5]
참고: <https://www.facebook.com/pyconkorea/posts/2611646412430895>

**Comment by dahlia** [comment]
@moreal 이건 언제 같이 볼까요?

**Comment by moreal** [comment]
> @moreal 이건 언제 같이 볼까요?

@dahlia 내일 데일리 끝나고 시간 괜찮으실까요?

**Comment by dahlia** [comment]
@moreal 네, 그럼 내일 오후 3시쯤에 얘기해보죠!
